FROM postgres AS donor
ENV PGDATA=/pgdata
COPY first.sql /docker-entrypoint-initdb.d/
RUN /docker-entrypoint.sh --help

FROM postgres AS main
ENV PGDATA=/pgdata
COPY --chown=postgres:postgres --from=donor /pgdata /pgdata