services:
  spring:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    labels:
      - "traefik.frontend.rule=Host:spring.docker.localhost"
    networks:
      - proxynet
  postgres:
    build:
      target: main
      context: .
      dockerfile: Dockerfile-dbx
    ports:
      - '5432:5432'
    labels:
      - "traefik.frontend.rule=Host:postgres.docker.localhost"
    networks:
      - proxynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
networks:
  proxynet:
    name: scripts_default
version: '3.5'
