services:
  spring:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    labels:
      - "traefik.frontend.rule=Host:spring.docker.localhost"
  postgres:
    image: postgres
    privileged: true
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    labels:
      - "traefik.frontend.rule=Host:postgres.docker.localhost"
#  dbtest:
#    image: 8deb96e5a73a
##    build:
##      context: .
##      dockerfile: Dockerfile-dbx
#    ports:
#    - '15432:5432'
#    labels:
#    - "traefik.frontend.rule=Host:dbtest.docker.localhost"
#  traefik:
#    image: traefik
#    command: --api --docker
#    ports:
#    - "180:80"
#    - "1443:443"
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
#    labels:
#    - "traefik.port=8080"
#    - "traefik.frontend.rule=Host:traefik.jen.local"
volumes:
  db:
    external: true
version: '3.4'
