services:
  spring:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    labels:
      - "traefik.frontend.rule=Host:spring.docker.localhost"
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    labels:
      - "traefik.frontend.rule=Host:postgres.docker.localhost"
  nexus:
    image: sonatype/nexus3
    ports:
      - '8083:8083'
    volumes:
      - 'nd:/nexus-data'
    labels:
      - "traefik.frontend.rule=Host:nexus.docker.localhost"
  git:
    image: gitlab/gitlab-runner
    labels:
    - "traefik.frontend.rule=Host:git.docker.localhost"
  jenkins:
    image: jenkinsci/blueocean
    user: root
#    privileged: true
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/masa:/home
    labels:
      - "traefik.frontend.rule=Host:jenkins.docker.localhost"
  traefik:
    image: traefik
    command: --api --docker
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host:traefik.docker.localhost"
volumes:
  db:
    external: true
  nd:
  jenkins:
  iq-data:
version: '3.3'
